export enum CountriesActionTypes {
  GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES',
  GET_ALL_COUNTRIES_ERROR = 'GET_ALL_COUNTRIES_ERROR',
  GET_ALL_COUNTRIES_LOADING = 'GET_ALL_COUNTRIES_LOADING',
}

export enum CreateUserTypes {
  CREATE_USER = 'CREATE_USER',
  CREATE_USER_ERROR = 'CREATE_USER_ERROR',
  CREATE_USER_LOADING = 'CREATE_USER_LOADING',
}

export enum LoginUserTypes {
  LOGIN = 'LOGIN',
  LOGIN_LOADING = 'LOGIN_LOADING',
  LOGIN_ERROR = 'LOGIN_ERROR',
}

export enum LogoutUserTypes {
  LOGOUT = 'LOGOUT',
  LOGOUT_ERROR = 'LOGOUT_ERROR',
}

export enum ResetPasswordTypes {
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING',
  RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR',
}

export enum CheckIfAdminTypes {
  CHECK_IF_ADMIN = 'CHECK_IF_ADMIN',
  CHECK_IF_ADMIN_ERROR = 'CHECK_IF_ADMIN_ERROR',
}

export enum GetCurrentUserTypes {
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR',
}

export enum GetUsersTypes {
  GET_USERS = 'GET_USERS',
  GET_USERS_LOADING = 'GET_USERS_LOADING',
  GET_USERS_ERROR = 'GET_USERS_ERROR',
}

export enum GetUserByIdTypes {
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  GET_USER_BY_ID_LOADING = 'GET_USER_BY_ID_LOADING',
  GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR',
}

export enum UpdateProfilePicTypes {
  UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC',
  UPDATE_PROFILE_PIC_LOADING = 'UPDATE_PROFILE_PIC_LOADING',
  UPDATE_PROFILE_PIC_ERROR = 'UPDATE_PROFILE_PIC_ERROR',
}

export enum UpdateUserTypes {
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_LOADING = 'UPDATE_USER_LOADING',
  UPDATE_USER_ERROR = 'UPDATE_USER_ERROR',
}

export enum DeleteUserTypes {
  DELETE_USER = 'DELETE_USER',
  DELETE_USER_LOADING = 'DELETE_USER_LOADING',
  DELETE_USER_ERROR = 'DELETE_USER_ERROR',
}

export const RESET_ERROR_SUCCESS = 'RESET_ERROR_SUCCESS';
